name: Shefing web site
title: Shefing Blog
email: contact@shefing.com
description: Innovation as a Service
baseurl: ""
url: "http://shefing.github.io"
github_username: philjoseph
email: "contact@shefing.com"
twitter_username: "philjosephcohen"

index:
  he: indexhe.html
  en:

t:
  en:
    section1:
          we: WE SHAPE
          ideas: ideas
          to: to
          life: life
          first: We are a boutique consulting agency, crafting software products for companies of all shapes and sizes.
          second: We love using our methodology and talents to transform ideas into reality. We use cutting edge cloud technologies and most performant front-end frameworks for web and mobile to ensure your satisfaction.
    section2:
          we: WE
          listen: LISTEN,
          design: DESIGN,
          develop: DEVELOP
          launch: LAUNCH
          content: We are a team composed of seasoned product executive, artisans crafting beautiful user interfaces and talented software developers passionated about creating disruptive products that engage users.
    section3:
          what: What make us
          special: Special
          effective: Effective
          effective-content: We focus on business goals, target audience, budget and time constraint to define the most effective product objectives.
          creative: Creative
          creative-content: We strive to create fluent user interfaces that will be intuitively understood by users, through multiple iterative prototypes before a single line of code is written.
          cutting-edge: Cutting edge
          cutting-edge-content: 'We develop modern Mobile and Web applications using the most advanced client technologies: Javascript, ReactJS, React-Nativeand Redux. On Mobile devices we produce truly native apps in a cost-effective way with a single code-base.'
          adaptive: Adaptive
          adaptive-content: We embrasse the Agile methodology and the 12 principles behind the Agile Manifesto, among them "Welcome changing requirements, even late in development".
          performant: Performant
          performant-content: We deploy Node.js to cutting edge PaaS providers such as Heroku to ensure evolutive, reliable and scalable operations. We leverage Google Firebase to create server less mobile and Web applications at the speed of light
          quality: Quality
          quality-content: We take responsibility on the quality of our deliveries by testing in-house. We never delegate this core responsibility to assess the quality.
          sustainable: Sustainable
          sustainable-content: We automate the DevOps to ensure long running applications in production, with high availability and minimal overhead.
    section4:
          meet: Meet our team
          content: We are a boutique consulting agency composed of product strategist, designer and developers with an extensive experience in building successful software products.
          phil: PHILIPPE COHEN
          phil-des: Product Strategist
          phil-content: Software engineering and ergonomics expert, he brings his experience to create the most efficient platform for companies of all shapes and sizes.
          footer: Have an idea you’d like to ship?
    global:
          english: English
          hebrew: עברית
  he:
    section1:
        we: הופכים
        ideas: רעיונות
        life: למציאות
        first: אנחנו חברת בוטיק לייעוץ ושירותים בונים מוצרי תוכנה ללקוחות שונים וגוונים.
        second: אנחנו אוהבים להשתמש במקצועיות ובכישרונות שלנו כדי להפוך רעיונות למציאות. אנחנו משתמשים בטכנולוגיות חדישות בתחום הענן והממשק משתמש כדי להבטיח את שביעות רצונך.
    section2:
        we: ' '
        listen: מקשיבים,
        design: מעצבים,
        develop: מתכנתים
        launch: מעלים
        content: אנחנו צוות המורכב בבכירי תעשית התוכנה ,מומחי עיצוב ומפתחי תוכנה מוכשרים הנלהבים ליצור מוצרים שימשכו לקוחות
    section3:
        what: מה שמייחד
        special: אותנו
        effective: יעילות
        effective-content: אנחנו מתמקדים במטרות העסקיות, קהל יעד, בתקציב ובלוחות הזמנים כדי להגדיר את מפת הדרכים שלכם.
        creative: יצירתיות
        creative-content: אנחנו שואפים ליצור זרימת מסכים נוחה אשר תובן באופן אינטואיטיבי על ידי המשתמשים,
        cutting-edge: חזית הטכנולוגיה
        cutting-edge-content: 'אנחנו מפתחים  ואפליקציות מודרניים Web ו-Mobile באמצעות טכנולוגיות client המתקדמות ביותר: Javascript, ReactJS, React-Native & Redux.  עבור מכשירים ניידים אנחנו מייצרים ישומים  native אמיתיים ובצורה חסכונית עם קוד משותף לכל הפלטפורמות.'
        adaptive: גמישות
        adaptive-content: אנחנו מאמצים את המתודולוגיה Agile ואת 12 העקרונות מאחוריה,  ביניהם "מקדמים בברכה שינויים בדרישות התוכנה, אפילו בשלב מתקדם של הפיתוח.".
        performant: ביצועים
        performant-content: אנחנו מעלים את Node.js לספקי PaaS מתקדמים כגון Heroku כדי להבטיח תפעול גמיש, אמין ומוכן לעומסים. אנחנו משתמשים ב-Google Firebase כדי ליצור שרת במהירות הבזק
        quality: איכות
        quality-content: אנחנו לוקחים אחריות על איכות המוצרים שלנו על ידי בדיקות פנימיות ולא נוציא החוצה את בדיקות האיכות.
        sustainable: פיתוח בר קיימא
        sustainable-content: אנחנו הופכים את DevOps לאוטומטי כדי להבטיח שהאפליקציות ירוצו לטווח ארוך אצל הלקוח, עם זמינות גבוהה ומינימום תקורות.
    section4:
        meet: הצוות שלנו
        content: אנחנו צוות המורכב ממנהל מוצר מנוסה ומפתחים עם ניסיון רב בבניית תוכנות מעולות.
        phil: פיליפ כהן
        phil-des: אסטרטג מוצרים
        phil-content:  מהנדס תוכנה ומומחה לארגונומיה, פיליפ מביא את ניסיונו ליצור את הפלטפורמה היעילה ביותר עבור חברות מכל הסוגים.
        footer: יש לך רעיון לשלוח?
    global:
        english: English
        hebrew: עברית
