name: Shefing web site

plugins: 
  - jekyll-multiple-languages-plugin

languages: ["en", "he"]

title: Shefing Blog
email: contact@shefing.com
description: Innovation as a Service
baseurl: ""
url: ""
github_username: philjoseph
email: "contact@shefing.com"
twitter_username: "philjosephcohen"
