name: Shefing web site

plugins: 
  - jekyll-multiple-languages-plugin

languages: ["en", "he"]

baseurl: ""
title: Shefing Blog
email: contact@shefing.com
description: Innovation as a Service
baseurl: ""
url: "http://blog.shefing.com/"
github_username: philjoseph
email: "contact@shefing.com"
twitter_username: "philjosephcohen"
